# Generated by Django 4.0.6 on 2022-08-25 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorygroup',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_relations', to='app_control.inventorygroup'),
        ),
    ]
