# Generated by Django 4.0.6 on 2022-08-26 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_control', '0003_alter_inventory_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 26, 22, 7, 47, 374147)),
        ),
    ]
